### ISSUE TITLE
Query generation not generating nullable types

### ISSUE THREAD

**Issue by bedeio** [knq/xo#94] opened 2017-04-03 02:11 UTC
```
go version go1.8 linux/amd64
psql (PostgreSQL) 9.6.2
Ubuntu 14.04.5 LTS
```
We're having trouble generating the go code for queries that select from multiple tables and/or views. Sample code and schema are below. 

*SQL*
```
BEGIN;
CREATE TABLE "occurence_date" (
        occurence_date_id SERIAL PRIMARY KEY, 
        occurence_date DATE UNIQUE
);

CREATE TABLE "note" (
        note_id SERIAL PRIMARY KEY, 
        note TEXT
);

CREATE TABLE "user_case" (
        user_case_id SERIAL PRIMARY KEY, 
        occurence_date_id INTEGER NOT NULL REFERENCES occurence_date("occurence_date_id"), 
        note_id INTEGER REFERENCES note("note_id")
);
COMMIT;
```
*CLI*
```

xo pgsql://postgres:justice@127.0.0.1/pddb -N -M -B -T SampleDateID -o $GOPATH/src/nycds-database/pddb/models/ << ENDSQL
SELECT occurence_date, note 
FROM user_case 
LEFT JOIN note USING (note_id) 
LEFT JOIN occurence_date USING (occurence_date_id) 
ENDSQL
```

The created go file `sampledateid.xo.go` generates `string` as a type for the `note` field although in the database the type allows for `NULL`s. We expected it would generate a `sql.NullString`, but weren't able to find a way to set the type.

**Comment by kenshaw** [comment] 2017-04-03 02:56
I'll take a look and see what the issue is.

**Comment by gajbotelho** [comment] 2017-04-09 20:32
Any luck? Thanks!

**Comment by kenshaw** [comment] 2017-04-19 04:20
Sorry, finally got around to this. This is an issue that actually I was aware of before, and I had added the `--query-fields` command line option so that one could manually override the types used. I know this is not ideal, but at least it can work temporarily. I'm trying to figure out where if I can fix the logic associated with this.

**Comment by kenshaw** [comment] 2017-04-19 04:27
Not sure if I can fix this or not. I know where in the code this happens, but I'm doing regression tests now on a bunch of different projects where this tool is used to see what the "effect" of fixing this is, if any.

**Comment by kenshaw** [comment] 2017-04-19 04:45
This has been fixed by adding a `--query-allow-nulls` command-line option. Please note that not all databases will end up respecting this properly, primarily due to the "clever hack" xo uses to extract information about a query. I would highly recommend forcing the specific types via the `--query-fields` option, however, as it makes it more explicit about what is intended, and a developer will more readily be able to understand the discrepancy/relationship between the schema design and the code.

Note: this is not enabled by default, as I want to maintain backwards compatibility with the existing tool. The reason I had originally designed / done it like this, is for a variety of philosophical reasons when it comes down to database design (which don't need to be discussed here). 

The `xo` code is really due for an overhaul ... !

**Closed by kenshaw** 2017-04-19 04:45 UTC
